---
title: "Spains's Battle with COVID-19"
author: "David J Jackson"
date: "09/10/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE)
options(scipen=5)
library(RSQLite)
```
```{r}
rm(list=ls())
source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
df <- dbGetQuery(db,"select * from ECDC")
df <- subset(df,Countries =="Spain" & Cases >0 )
df$Reported <- as.Date(df$Reported)
mean(df$Cases)
mean(df$Deaths)

```
```{r}
US <- subset(df,Reported >="2020-04-01")
US <- df[order(df$Reported,decreasing = TRUE),]
# summary(US$Cases)
#summary(US$Deaths)
US$MA14 <- movingAverage(US$Cases,14)
plot(US$Reported,US$Cases,type="l",main=" COVID-19 Cases Apr. 1,2020 - Pesent",
     xlab="Date Reported",ylab="Cases")
lines(US$Reported,US$MA14,col="red")
grid(col="black")
```
```{r}
#US <- subset(df,Reported >="2020-04-01" & Reported <="2020-09-09")
US$Deaths14 <- movingAverage(US$Deaths,14)
plot(US$Reported,US$Deaths,type="l",main="COVID-19 Deaths Apr. 1,2020 - Present",
     xlab="Date Reported",ylab="Deaths and 14 day Moving Averges(red)")
lines(US$Reported,US$Deaths14,col="red")
grid(col="black")
```

## Beginning with June 1, 2020

```{r}
USA <- subset(US,Reported >="2020-06-01")
USA$MA14 <- movingAverage(USA$Cases,14)
plot(USA$Reported,USA$Cases,type="l",main=" COVID-19 Cases June. 1,2020 - Sept, 7, 2020",
     xlab="Date Reported",ylab="Cases")
lines(US$Reported,US$MA14,col="red")
grid(col="black")
```


#### Non-Moving Average By Week and By Month

```{r}
US$Monthly <- as.Date(cut(US$Reported,
  breaks = "month"))
US$Weekly <- as.Date(cut(US$Reported,
  breaks = "week",
  start.on.monday = FALSE))

```
```{r}
Weekly_Cases <- aggregate(Cases~Weekly,US,FUN=sum)
Weekly_Deaths <- aggregate(Deaths~Weekly,US,FUN=sum)
Weekly_Cases$DRate <- Weekly_Deaths$Deaths/Weekly_Cases$Cases
Weekly_Cases$LivedSaved <- Weekly_Cases$Cases * (max(Weekly_Cases$DRate) - Weekly_Cases$DRate) * 100

```
```{r}
barplot(Cases ~Weekly,data=Weekly_Cases,main="Weekly COVOD-19 Cases",xlab="Weekly Date",ylab="Cases")
grid(col="black")
barplot(Deaths ~Weekly,data=Weekly_Deaths,main="Weekly COVID-19 Deaths",
        xlab="Weekly Date",ylab="Deaths")
grid(col="black")

barplot(DRate ~Weekly,data=Weekly_Cases,main="Weekly Change in Deaths Rates",
        xlab="Weekly Date",ylab="Cases")
grid(col="black")

# barplot(LivedSaved ~Weekly,data=Weekly_Cases,main="Estimated Lives Saved Per Week",
#         xlab="Weekly Date",ylab="Est. Lives Saved")
# grid(col="black")
```

###  Monthly Deaths Rate i.e. Deaths/Cases

```{r}

Monthly_Cases <- aggregate(Cases~Monthly,US,FUN=sum)
Monthly_Deaths <- aggregate(Deaths~Monthly,US,FUN=sum)
Monthly_Cases$DRate <- Monthly_Deaths$Deaths/Monthly_Cases$Cases
Monthly_Cases$LivedSaved <- Monthly_Cases$Cases * (max(Monthly_Cases$DRate) - Monthly_Cases$DRate) * 100

```
```{r}
barplot(Cases ~Monthly,data=Monthly_Cases,main="Monthly Total Cases",
        xlab="Months",ylab="Monthly Cases")
grid(col="black")
barplot(Deaths ~Monthly,data=Monthly_Deaths,main="Monthly Total Deaths",
        xlab="Months",ylab="Monthly Deaths")
grid(col="black")

barplot(DRate ~Monthly,data=Monthly_Cases,main="Monthly Deaths Rates",
        xlab="Months",ylab=" Death Rate %")
grid(col="black")

# barplot(LivedSaved ~Monthly,data=Monthly_Cases,main="Estimated Lives Saved",
#         xlab="Months",ylab="Est. Lives Saved")
# grid(col="black")
```

### Weekly and Monthly Mean COVID-19 Cases And Deaths

```{r}
Weekly_Cases <- aggregate(Cases~Weekly,US,FUN=mean)
Weekly_Deaths <- aggregate(Deaths~Weekly,US,FUN=mean)
```
```{r}
barplot(Cases ~Weekly,data=Weekly_Cases,main="Weekly Mean Cases",
        xlab="Weekly Date",ylab="Mean/Average Cases")
grid(col="black")
barplot(Deaths ~Weekly,data=Weekly_Deaths,main="Weekly Mean Deaths",
        xlab="Weekly Date",ylab="Mean/Average Cases")
grid(col="black")
```
```{r}
Monthly_Cases <- aggregate(Cases~Monthly,US,FUN=mean)
Monthly_Deaths <- aggregate(Deaths~Monthly,US,FUN=mean)
```
```{r}
barplot(Cases ~Monthly,data=Monthly_Cases,main="Monthly Mean Cases",
        xlab="Monthly Date",ylab="Mean/Average Cases")

barplot(Deaths ~Monthly,data=Monthly_Deaths,main="Monthly Mean Deaths",
          xlab="Month Date",ylab="Mean/Average Deaths")
grid(col="black")
```
## Case-Fatality_Ratio and Incidence_Rate

```{r}
# df$Ratio <- df$Cases/df$Deaths 
# Fatality <- subset(df,Reported >="2020-06-01")
# plot(Fatality$Reported,Fatality$Ratio,type="l", main="Case-Fatality_Ratio")
# grid(col="black")
```
